title: Terry's Reviews
description: Trusted, in-depth product reviews by Terry
remote_theme: jekyll/minima

plugins:
  - jekyll-sitemap

sass:
  sass_dir: assets/css        # where your .scss files live
  style: compressed           # output style: nested, expanded, compact, or compressed



