title: Terry's Reviews
description: Trusted, in-depth product reviews by Terry
remote_theme: jekyll/minima

url: "https://www.revuary.co.uk"   # your siteâ€™s root URL, always with https
baseurl: ""                      # leave empty unless your site is served from a subpath


plugins:
  - jekyll-sitemap

sass:
  sass_dir: assets/css        # where your .scss files live
  style: compressed           # output style: nested, expanded, compact, or compressed
  



